### ISSUE TITLE
Still issuing for size distribution plot

### ISSUE THREAD

**Issue by yuriljx** [niallrobinson/wasp#6]
So I tried the updated version, For To Do function, you can edit the start pt and end pt for time selection. The software can generate a modified time series plot.  This part works well. 
But if you select any sizes, even highlight all of them, and then make a new file to see the size distribution, the graph is still blank. 
![image](https://f.cloud.github.com/assets/6556945/2078435/0adca948-8dbe-11e3-8839-f77cd1760671.png)

**Comment by niallrobinson** [comment]
Hi Yuri - should be fixed now. It was just that the panel in the template file hadn't been updated. You can redownload the latest version, or alternatively, just close the panel, and then reopen it from the dropdown wasp menu
